### PR TITLE
Vtol

### PR DESCRIPTION
**Pull request by shovan777**
#26 Enable standard vtol simulation with ardupilot.

### CODE REVIEW

**Review by SwiftGust — CHANGES_REQUESTED** [review]
Hi, Thank you for making PR @shovan777.
Could you only leave models/standard_vtol/standard_vtol.* and 
remove other unrelated files such as ArduPilot log?

**Comment by shovan777** [comment]
> Hi, Thank you for making PR @shovan777.
> Could you only leave models/standard_vtol/standard_vtol.* only and
> remove other unrelated files such as ArduPilot log?

Hi @SwiftGust, I just made your requested changes and cleaned up everything except the standard_vtol* files.

**Comment by SwiftGust** [comment]
Hi @shovan777 I'll make time to review this PR soon, can you upload default parameter for this airframe in the comment?

**Comment by shovan777** [comment]
Hi @SwiftGust, here is the file: 
[gazebo-quadplane.parm.tar.gz](https://github.com/SwiftGust/ardupilot_gazebo/files/5178935/gazebo-quadplane.parm.tar.gz)

**Comment by SwiftGust** [comment]
Hi @shovan777,
I have tested this quadplane in Auto mode and this flies well.
I think we should also include minimum stall speed (seems 17 m/s) as default parameter
ARSPD_FBW_MIN 20
and may need increase pusher thrust or wing lift which I can handle.

Great work! Thank you for PR.

**Comment by shovan777** [comment]
> Hi @shovan777,
> I have tested this quadplane in Auto mode and this flies well.
> I think we should also include minimum stall speed (seems 17 m/s) as default parameter
> ARSPD_FBW_MIN 20
> and may need increase pusher thrust or wing lift which I can handle.
> 
> Great work! Thank you for PR.

Hi @SwiftGust,
Great news!!!! thank u.

**Pull request merged**
